'use client';
import { useEffect, useMemo, useState } from 'react';

type BU={id:string;name:string;code:string;kind:string}; type Account={id:string;name:string;type:string;business_unit_id:string|null;is_personal:boolean;opening_balance:number;currency:string}; type Cat={id:string;name:string;type:string}; type Tx=any;
const money=(n:number)=>new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP'}).format(n||0);
const empty={transaction_date:new Date().toISOString().slice(0,10),type:'expense',amount:'',category_id:'',account_id:'',description:'',reference_number:'',counterparty:'',business_unit_id:'',is_personal:false,tax_type:'none',tax_inclusive:true,notes:''};
export default function Home(){const [tab,setTab]=useState('dashboard');const [bus,setBus]=useState<BU[]>([]);const [accounts,setAccounts]=useState<Account[]>([]);const [cats,setCats]=useState<Cat[]>([]);const [workspace,setWorkspace]=useState('whole');const [tx,setTx]=useState<Tx[]>([]);const [summary,setSummary]=useState<any>({});const [balances,setBalances]=useState<any[]>([]);const [q,setQ]=useState('');const [show,setShow]=useState(false);const [form,setForm]=useState<any>(empty);const [editing,setEditing]=useState<string|null>(null);const [loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);const m=await fetch('/api/meta').then(r=>r.json());setBus(m.businessUnits||[]);setAccounts(m.accounts||[]);setCats(m.categories||[]);const qs=workspace==='whole'?'':workspace==='personal'?'&personal=true':`&business_unit_id=${workspace}`;const [t,s,b]=await Promise.all([fetch(`/api/transactions?q=${encodeURIComponent(q)}${qs}`).then(r=>r.json()),fetch(`/api/summary?business_unit_id=${workspace}`).then(r=>r.json()),fetch('/api/balances').then(r=>r.json())]);setTx(Array.isArray(t)?t:[]);setSummary(s||{});setBalances(Array.isArray(b)?b:[]);setLoading(false)};
 useEffect(()=>{load()},[workspace,q]);
 const selected=bus.find(x=>x.id===workspace);const title=workspace==='whole'?'Whole / All Companies':selected?.name||'Company Admin Hub';
 function openNew(){setEditing(null);setForm({...empty,business_unit_id:workspace==='whole'?'':workspace});setShow(true)}
 function openEdit(x:any){setEditing(x.id);setForm({...x,amount:String(x.amount),business_unit_id:x.business_unit_id||'',category_id:x.category_id||'',account_id:x.account_id||'',is_personal:!!x.is_personal});setShow(true)}
 async function save(){const r=await fetch(editing?`/api/transactions/${editing}`:'/api/transactions',{method:editing?'PATCH':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(form)});if(!r.ok){alert((await r.json()).error||'Could not save');return}setShow(false);await load()}
 async function del(id:string){if(!confirm('Delete this transaction?'))return;const r=await fetch(`/api/transactions/${id}`,{method:'DELETE'});if(!r.ok)alert((await r.json()).error||'Could not delete');await load()}
 const companyButtons=[...bus.filter(x=>x.kind==='company')]; const nav=[['dashboard','Dashboard'],['transactions','Transactions'],['balances','Balances / Fintech'],['vat','VAT / Tax'],['reports','Monthly Tally']];
 return <div className="shell"><header className="top"><div className="brand">Company Admin Hub</div><div style={{display:'flex',gap:10,alignItems:'center'}}><span style={{fontSize:13,opacity:.8}}>{title}</span><button onClick={async()=>{await fetch('/api/logout',{method:'POST'});location.href='/login'}}>Log out</button></div></header><div className="layout"><aside><div className="nav">{nav.map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div></aside><main className="main"><div className="workspace"><button className={workspace==='whole'?'selected':''} onClick={()=>setWorkspace('whole')}>Whole / All</button>{companyButtons.map(x=><button key={x.id} className={workspace===x.id?'selected':''} onClick={()=>setWorkspace(x.id)}>{x.name}</button>)}<button className={workspace==='personal'?'selected':''} onClick={()=>setWorkspace('personal')}>Personal / Other</button></div>{tab==='dashboard'&&<><div className="head"><div><h1>{title}</h1><div className="muted">Internal financial and transaction control center</div></div><button className="btn" onClick={openNew}>+ New transaction</button></div><div className="grid"><div className="card"><div className="label">Income</div><div className="value positive">{money(summary.income)}</div></div><div className="card"><div className="label">Expenses</div><div className="value negative">{money(summary.expenses)}</div></div><div className="card"><div className="label">Net</div><div className="value">{money(summary.net)}</div></div><div className="card"><div className="label">Net VAT</div><div className="value">{money(summary.net_vat)}</div></div></div><div className="panel"><h3>Monthly tally</h3><table className="table"><thead><tr><th>Month</th><th>Income</th><th>Expenses</th><th>Net</th><th>Output VAT</th><th>Input VAT</th></tr></thead><tbody>{(summary.monthly||[]).map((m:any)=><tr key={m.month}><td>{m.month}</td><td>{money(m.income)}</td><td>{money(m.expenses)}</td><td>{money(m.income-m.expenses)}</td><td>{money(m.output_vat)}</td><td>{money(m.input_vat)}</td></tr>)}</tbody></table></div></>}
 {tab==='transactions'&&<><div className="head"><div><h1>Transactions</h1><div className="muted">Company transactions and personal charges can coexist on the same bank account.</div></div><button className="btn" onClick={openNew}>+ New transaction</button></div><div className="panel"><div className="toolbar"><input placeholder="Search description, reference, person…" value={q} onChange={e=>setQ(e.target.value)}/><button className="btn secondary" onClick={load}>Refresh</button></div><table className="table"><thead><tr><th>Date</th><th>Type</th><th>Company</th><th>Personal</th><th>Description</th><th>Account</th><th>Amount</th><th></th></tr></thead><tbody>{tx.map(x=><tr key={x.id}><td>{x.transaction_date}</td><td>{x.type}</td><td>{x.business_units?.name||'—'}</td><td>{x.is_personal?'Yes':'No'}</td><td>{x.description||'—'}</td><td>{x.accounts?.name||'—'}</td><td>{money(x.amount)}</td><td><button className="btn secondary" onClick={()=>openEdit(x)}>Edit</button> <button className="btn danger" onClick={()=>del(x.id)}>Delete</button></td></tr>)}</tbody></table></div></>}
 {tab==='balances'&&<><div className="head"><div><h1>Balances / Fintech foundation</h1><div className="muted">Opening balance + transaction movement. Personal transactions still affect the real bank balance.</div></div></div><div className="grid">{balances.map(b=><div className="card" key={b.id}><div className="label">{b.name}</div><div className="value">{money(Number(b.current_balance))}</div><div className="muted">{b.currency} · {b.is_personal?'Personal':'Company-linked'}</div></div>)}</div></>}
 {tab==='vat'&&<><div className="head"><div><h1>VAT / Tax</h1><div className="muted">Fixed 12% VAT for now. Income contributes to Output VAT; expenses contribute to Input VAT.</div></div></div><div className="grid"><div className="card"><div className="label">Output VAT</div><div className="value">{money(summary.output_vat)}</div></div><div className="card"><div className="label">Input VAT</div><div className="value">{money(summary.input_vat)}</div></div><div className="card"><div className="label">Net VAT</div><div className="value">{money(summary.net_vat)}</div></div></div></>}
 {tab==='reports'&&<><div className="head"><div><h1>Monthly Tally</h1><div className="muted">Use the workspace buttons above to switch between Bringing Industry Solution, Bethesher, Whole, and Personal / Other.</div></div></div><div className="panel"><table className="table"><thead><tr><th>Month</th><th>Transactions</th><th>Income</th><th>Expenses</th><th>Net</th></tr></thead><tbody>{(summary.monthly||[]).map((m:any)=><tr key={m.month}><td>{m.month}</td><td>{m.count}</td><td>{money(m.income)}</td><td>{money(m.expenses)}</td><td>{money(m.income-m.expenses)}</td></tr>)}</tbody></table></div></>}
 {loading&&<div className="muted" style={{marginTop:16}}>Loading…</div>}</main></div>{show&&<div className="modal"><div className="modalbox"><h2>{editing?'Edit transaction':'New transaction'}</h2><div className="form"><label>Date<input type="date" value={form.transaction_date} onChange={e=>setForm({...form,transaction_date:e.target.value})}/></label><label>Type<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="income">Income</option><option value="expense">Expense</option></select></label><label>Amount<input type="number" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>VAT<select value={form.tax_type} onChange={e=>setForm({...form,tax_type:e.target.value})}><option value="none">No VAT</option><option value="vat">VAT 12%</option></select></label><label>Company<select value={form.business_unit_id} onChange={e=>setForm({...form,business_unit_id:e.target.value})}><option value="">Unassigned</option>{companyButtons.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Account<select value={form.account_id} onChange={e=>setForm({...form,account_id:e.target.value})}><option value="">No account</option>{accounts.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Category<select value={form.category_id} onChange={e=>setForm({...form,category_id:e.target.value})}><option value="">No category</option>{cats.filter(c=>c.type===form.type).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Counterparty<input value={form.counterparty||''} onChange={e=>setForm({...form,counterparty:e.target.value})}/></label><label>Reference<input value={form.reference_number||''} onChange={e=>setForm({...form,reference_number:e.target.value})}/></label><label className="full">Description<input value={form.description||''} onChange={e=>setForm({...form,description:e.target.value})}/></label><label className="full"><span>Personal expense <input type="checkbox" checked={!!form.is_personal} onChange={e=>setForm({...form,is_personal:e.target.checked})}/></span></label><label className="full">Notes<textarea value={form.notes||''} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div><div className="actions"><button className="btn secondary" onClick={()=>setShow(false)}>Cancel</button><button className="btn" onClick={save}>Save transaction</button></div></div></div>}</div>}
